create table if not exists users (
  uid integer primary key,
  name varchar unique not null,
  password varchar not null
);

create table if not exists permission_meta (
  permission_code integer primary key,
  display_name varchar not null,
  description varchar not null
);

create table if not exists permission_include (
  permission_code integer not null references permission_meta(permission_code) on delete cascade,
  permission_code_included integer not null references permission_meta(permission_code) on delete cascade,
  primary key (permission_code, permission_code_included)
);

create table if not exists user_permission (
  uid integer not null references users(uid) on delete cascade,
  permission_code integer not null references permission_meta(permission_code) on delete cascade,
  primary key (uid, permission_code)
);

create table if not exists service_permission_meta (
  service_id varchar not null,
  permission_code integer not null,
  display_name varchar not null,
  description varchar not null,
  primary key (service_id, permission_code)
);

create table if not exists service_permission_include (
  service_id varchar not null,
  permission_code integer not null,
  permission_code_included integer not null,
  primary key (service_id, permission_code, permission_code_included),
  foreign key (service_id, permission_code) references service_permission_meta(service_id, permission_code) on delete cascade,
  foreign key (service_id, permission_code_included) references service_permission_meta(service_id, permission_code) on delete cascade
);

create table if not exists user_service_permission (
  uid integer not null references users(uid) on delete cascade,
  service_id varchar not null,
  permission_code integer not null,
  primary key (uid, service_id, permission_code),
  foreign key (service_id, permission_code) references service_permission_meta(service_id, permission_code) on delete cascade
);

insert into permission_meta(permission_code, display_name, description) values
  (1001, 'User Read', 'Read users and their permission assignments.'),
  (1002, 'User Create', 'Create users.'),
  (1003, 'User Edit', 'Edit users and user permission assignments.'),
  (1004, 'User Delete', 'Delete users.'),
  (1099, 'User Manage', 'All user management permissions.'),
  (1101, 'Token Read', 'Read token records.'),
  (1102, 'Token Issue', 'Issue tokens for users.'),
  (1103, 'Token Revoke', 'Actively invalidate tokens.'),
  (1104, 'Token Delete', 'Delete token records.'),
  (1199, 'Token Manage', 'All token management permissions.')
on conflict (permission_code) do nothing;

insert into permission_include(permission_code, permission_code_included) values
  (1099, 1001),
  (1099, 1002),
  (1099, 1003),
  (1099, 1004),
  (1099, 1199),
  (1199, 1101),
  (1199, 1102),
  (1199, 1103),
  (1199, 1104)
on conflict (permission_code, permission_code_included) do nothing;

create table if not exists key_pairs (
  id integer primary key generated by default as identity,
  private_key varchar not null,
  public_key varchar not null,
  created_at bigint not null,
  created_at_timezone integer not null,
  is_active boolean default true
);

create table if not exists jwt_tokens (
  jti varchar(36) primary key,
  uid integer not null references users(uid) on delete cascade,
  created_at bigint not null,
  created_at_timezone integer default 0,
  expires_at bigint not null,
  jwt_token varchar not null,
  status_code integer default 1 not null,
  revoked_at bigint
);
